### ISSUE TITLE
 ImportError: cannot import name set_id_type_array

### ISSUE THREAD

**Issue by RuiqinZheng** [seqcode/miniMDS#11]
Hello,
Thanks for your software!
But when I type "import plotting" ,I got some errors:
>>> import plotting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plotting.py", line 1, in <module>
    from mayavi import mlab
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/mayavi/mlab.py", line 15, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.base import Base
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/mayavi/core/base.py", line 19, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/tvtk/pyface/tvtk_scene.py", line 28, in <module>
    from tvtk.pyface import light_manager
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 130, in <module>
    class CameraLight(HasTraits):
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 146, in CameraLight
    source = Instance(tvtk.Light, ())
  File "tvtk_classes/tvtk_helper.py", line 234, in <lambda>
  File "tvtk_classes/tvtk_helper.py", line 36, in get_class
  File "tvtk_classes/tvtk_helper.py", line 28, in get_module
  File "tvtk_classes/light.py", line 12, in <module>
  File "/public/home/rqzheng/anaconda2/lib/python2.7/site-packages/tvtk/array_handler.py", line 28, in <module>
    from tvtk.array_ext import set_id_type_array
ImportError: cannot import name set_id_type_array

I try to updata my python package including numpy and scipy, but that doesn't work.
can you help me how to solve it?

sincerely 
Ruiqin Zheng

**Comment by RuiqinZheng** [comment]
I have solved it !
Thanks
