### ISSUE TITLE
IndexError when running minimds_inter.py script

### ISSUE THREAD

**Issue by shenlinyong** [seqcode/miniMDS#21]
The software you developed is fantastic, but I had trouble building 3D models between chromosomes.
```bash
856 Reading ../../data/fat/fat_36_Z_1.0mb.bed
    857 Reading ../../data/fat/fat_37_Z_1.0mb.bed
    858 Reading ../../data/fat/fat_38_Z_1.0mb.bed
    859 Reading ../../data/fat/fat_39_Z_1.0mb.bed
    860 Reading ../../data/fat/fat_Z_100kb.bed
    861 Scanning ../../data/fat/fat_1_100kb.bed
    862 Traceback (most recent call last):
    863   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 168, in <module>
    864     main()
    865   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 158, in main
    866     structures = interMDS(chrom_names, args.prefix, args.inter_res, args.intra_res, args.partitioned, params)
    867   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 111, in interMDS
    868     r, t = la.getTransformation(inferred_low, true_low)
    869   File "/home/SLY68/biosoft/miniMDS/linear_algebra.py", line 13, in getTransformation
    870     a.append(structure1.points[num-structure1.offset].pos)
    871 IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
    872 Scanning ../../data/lean/lean_1_100kb.bed
    873 Scanning ../../data/lean/lean_2_100kb.bed
    874 Scanning ../../data/lean/lean_3_100kb.bed
    875 Scanning ../../data/lean/lean_4_100kb.bed
    876 Scanning ../../data/lean/lean_5_100kb.bed
```

Here is my running script:
```bash
python ~/biosoft/miniMDS/minimds_inter.py -n 50 ../../data/fat/fat 1000000 100000
python ~/biosoft/miniMDS/minimds_inter.py -n 50 ../../data/lean/lean 1000000 100000
```

**Comment by Alexlsy** [comment]
The cause of this error is that "num", "structure1.offset" and "structure2.offset" become float.
replace 
a.append(structure1.points[num-structure1.offset].pos)
a.append(structure2.points[num-structure2.offset].pos)
(in linear_algebra.py)
with
a.append(structure1.points[int(num)-int(structure1.offset)].pos)
b.append(structure2.points[int(num)-int(structure2.offset)].pos)

can solve this error

**Comment by shenlinyong** [comment]
Thank you very much for your help. I have modified :
```bash
replace
a.append(structure1.points[num-structure1.offset].pos)
a.append(structure2.points[num-structure2.offset].pos)
(in linear_algebra.py)
with
a.append(structure1.points[int(num)-int(structure1.offset)].pos)
b.append(structure2.points[int(num)-int(structure2.offset)].pos)
```
 I'm still having trouble:
```bash
   1762 Reading ../../data/lean/lean_39_Z_1.0mb.bed
   1763 Reading ../../data/lean/lean_Z_100kb.bed
   1764 Scanning ../../data/lean/lean_1_100kb.bed
   1765 /home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
   1766   out=out, **kwargs)
   1767 /home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
   1768   ret = ret.dtype.type(ret / rcount)
   1769 Scanning ../../data/lean/lean_2_100kb.bed
   1770 Scanning ../../data/lean/lean_3_100kb.bed
....
   1796 Scanning ../../data/lean/lean_29_100kb.bed
   1797 Traceback (most recent call last):
   1798   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 168, in <module>
   1799     main()
   1800   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 158, in main
   1801     structures = interMDS(chrom_names, args.prefix, args.inter_res, args.intra_res, args.partitioned, params)
   1802   File "/home/SLY68/biosoft/miniMDS/minimds_inter.py", line 106, in interMDS
   1803     rescaling_factor = la.radius_of_gyration(true_low)/la.radius_of_gyration(inferred_low)
   1804   File "/home/SLY68/biosoft/miniMDS/linear_algebra.py", line 46, in radius_of_gyration
   1805     return dist_sum/len(coords)
   1806 ZeroDivisionError: division by zero
```

**Comment by Lila14** [comment]
> The cause of this error is that "num", "structure1.offset" and "structure2.offset" become float. replace a.append(structure1.points[num-structure1.offset].pos) a.append(structure2.points[num-structure2.offset].pos) (in linear_algebra.py) with a.append(structure1.points[int(num)-int(structure1.offset)].pos) b.append(structure2.points[int(num)-int(structure2.offset)].pos)
> 
> can solve this error

Thanks, I fixed this!

**Comment by Lila14** [comment]
It looks like somehow a structure ended up empty. I noticed that you're using a nonhuman genome, I wonder if one of the chromosomes is shorter than 1Mb and couldn't be reduced to that resolution? If you send me the input files I can test.

**Comment by shenlinyong** [comment]
> 看起来不知何故，一个结构最终是空的。我注意到您使用的是非人类基因组，我想知道其中一条染色体是否短于 1Mb 并且无法降低到该分辨率？如果你把我可以测试的输入文件发给我。

You are right, some chromosomes are less than 1M in length. The smallest chromosome is only 0.17Mb and the largest chromosome is 196Mb. Therefore, what is the suitable resolution of hic data to use when constructing the 3D structure:
```bash
chr1    196449156
chr2    149539284
chr3    110642502
chr4    90861225
chr5    59506338
chr6    36220557
chr7    36382834
chr8    29578256
chr9    23733309
chr10   20453248
chr11   19638187
chr12   20119077
chr13   17905061
chr14   15331188
chr15   12703657
chr16   2706039
chr17   11092391
chr18   11623896
chr19   10455293
chr20   14265659
chr21   6970754
chr22   4686657
chr23   6253421
chr24   6478339
chr25   3067737
chr26   5349051
chr27   5228753
chr28   5437364
chr29   726478
chr30   755666
chr31   2457334
chr32   125424
chr33   3839931
chr34   3469343
chr35   554126
chr36   358375
chr37   157853
chr38   667312
chr39   177356
chrW    9109940
chrZ    86044486
```

**Comment by Lila14** [comment]
I would say try 100kb because that will mean no empty chromosomes
