### ISSUE TITLE
Got TypeError when I ran the test.

### ISSUE THREAD

**Issue by ghost** [seqcode/miniMDS#31]
Dear developer,

Thanks for providing this amazing tool for HiC data modeling! After installation, I ran testing on the sample data, however, I got TypeError as follows. I also tried my own data and got similar error. Could you provide some clues as to where this error comes from and how to fix it? Thank you very much!

command: bash test.sh 
Traceback (most recent call last):
  File "/LOCALSTORE/L_Space/yuz/hichip/hic_public/miniMDS/scripts/../minimds.py", line 170, in <module>
    main()
  File "/LOCALSTORE/L_Space/yuz/hichip/hic_public/miniMDS/scripts/../minimds.py", line 161, in main
    structure = fullMDS(args.path, args.classical, args.a, args.n, args.w)
  File "/LOCALSTORE/L_Space/yuz/hichip/hic_public/miniMDS/scripts/../minimds.py", line 43, in fullMDS
    contactMat = dt.matFromBed(path, structure=structure)
TypeError: matFromBed() got an unexpected keyword argument 'structure'

**Comment by Lila14** [comment]
My apologies, I recently refactored, which broke some things. I've fixed this bug. Please pull the latest code and try again.

**Comment by ghost** [comment]
Thanks for the prompt response! I ran the test on the latest version, and it seems the first command "**python ../minimds.py hic_data/GM12878_combined_22_5kb.bed**" works, however, the second command "**python ../minimds.py --partitioned hic_data/GM12878_combined_22_5kb.bed**" seems to be stuck and didn't not produce any output after 24 hours. I'm wondering if there's any problem with --partitioned feature? Thank you!

**Comment by Lila14** [comment]
Thank you for spotting this. It was an issue with the parallelization library I used. I removed parallelization for now and will replace it with another library.

**Comment by ghost** [comment]
<img width="759" alt="Screenshot 2024-06-11 at 3 52 15 PM" src="https://github.com/seqcode/miniMDS/assets/139503556/5f60a73f-caa4-4baf-bb7e-e6222f3855f7">

Thank you for the response! I tried minimds.py with my own data, and got the 3d model as I attached. The way I used this program is, first extract normalized intra-chromosome interactions to generate bed file for each chromosome, and then apply the minimds.py for each chromosome file to get a structure file, and use the plotting code you provided to visualize all chromosomes simultaneously. For the attached model I used 50k resolution, and only calculated intra-chromosome interactions. Just want to make sure with you, is it the correct way to use miniMDS? And if I use minimds_inter.py, will I got models that includes both inter- and intra-chromosome interactions? Thank you so much!

**Comment by Lila14** [comment]
It only makes sense to plot all chromosomes simultaneously if you've
calculated inter-chromosomal interactions using minimds_inter.py. If you
only used intra-chromosomal, plot each chromosome separately.

**Comment by ghost** [comment]
Thank you for the suggestions!
